source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import TaskIndex, TaskView, TaskCreate, TaskUpdate, TaskDelete, ProjectIndex, ProjectView, ProjectCreate, ProjectUpdate,  ProjectDelete, ProjectsLikes

app_name = 'webapp'

urlpatterns = [
    path('', ProjectIndex.as_view(), name='project_index'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project'),
    path('project/create/', ProjectCreate.as_view(), name='project_create'),
    path('project/update/<int:pk>/', ProjectUpdate.as_view(), name='project_update'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete'),

    path('task/index/', TaskIndex.as_view(), name='task_index'),
    path('task/<int:pk>/', TaskView.as_view(), name='task'),
    path('project/<int:pk>/create/task/', TaskCreate.as_view(), name='task_create'),
    path('task/update/<int:pk>/', TaskUpdate.as_view(), name='task_update'),
    path('task/delete/<int:pk>/', TaskDelete.as_view(), name='task_delete'),
    path('project/like/<int:pk>', ProjectsLikes.as_view(), name='project_like'),

]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


# Create your models here.
class Task(models.Model):
    summary = models.CharField(max_length=30, verbose_name="Заголовок")
    description = models.TextField(max_length=3000, verbose_name="Описание", null=True, blank=True)
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, related_name='statuses')
    type = models.ManyToManyField('webapp.Type', related_name='types')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата начала")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата окончания")
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='projects')
    likes = models.ManyToManyField(get_user_model(), related_name='tasks_likes', verbose_name='Лайки')

    def get_absolute_url(self):
        return reverse('webapp:task', kwargs={'pk': self.pk})


class Type(models.Model):
    name = models.CharField(max_length=30, verbose_name="Типы")

    def __str__(self):
        return f'{self.name}'


class Status(models.Model):
    name = models.CharField(max_length=30, verbose_name="Статус")

    def __str__(self):
        return f'{self.name}'


class Project(models.Model):
    author = models.ManyToManyField(get_user_model(), default=1, related_name='projects', verbose_name='Автор')
    created_at = models.DateField(verbose_name="Время создания")
    expiration_at = models.DateField(verbose_name="Время изменения", null=True, blank=True)
    summary = models.CharField(max_length=30, verbose_name="Заголовок")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    likes = models.ManyToManyField(get_user_model(), related_name='projects_likes', verbose_name='Лайки')

    def get_absolute_url(self):
        return reverse('webapp:project', kwargs={'pk': self.pk})

    class Meta:
        permissions = [('add_user_in_project', 'Добавить пользователя в проект'), ]

source/webapp/views.py
from django.db.models import Q
from django.utils.http import urlencode
from django.shortcuts import render, get_object_or_404, redirect, reverse
from webapp.models import Task
from django.views.generic import TemplateView, FormView, ListView
from webapp.form import TaskForm, SearchForm


# Create your views here.


class IndexViews(ListView):
    template_name = 'task/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ['-created_at']
    paginate_by = 10
    paginate_orphans = 5

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class TaskView(TemplateView):
    template_name = 'task/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = get_object_or_404(Task, pk=kwargs.get('pk'))
        return context


class TaskCreate(FormView):
    template_name = 'task/task_create.html'
    form_class = TaskForm

    def form_valid(self, form):
        types = form.cleaned_data.pop('type')
        self.task = Task.objects.create(**form.cleaned_data)
        self.task.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task', kwargs={'pk': self.task.pk})


class TaskUpdate(FormView):
    template_name = 'task/task_update.html'
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def get_initial(self):
        initial = {}
        for key in 'summary', 'description', 'status':
            initial[key] = getattr(self.task, key)
        initial['type'] = self.task.type.all()
        return initial

    def form_valid(self, form):
        types = form.cleaned_data.pop('type')
        for key, value in form.cleaned_data.items():
            if value is not None:
                setattr(self.task, key, value)
        self.task.save()
        self.task.type.set(types)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task', kwargs={'pk': self.task.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=pk)


class TaskDelete(TemplateView):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        return render(request, 'task/task_delete.html', {'task': task})

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        task.delete()
        return redirect('index')

source/webapp/views/project_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from webapp.models import Project
from webapp.form import ProjectForm
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse


class ProjectsLikes(View):
    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))

        data = {
            'like': project.likes.all().count(),
        }

        response = JsonResponse(data)
        print(project.likes.all().count())

        return response



class ProjectIndex(ListView):
    template_name = 'project/index.html'
    context_object_name = 'projects'
    model = Project
    paginate_by = 5


class ProjectView(LoginRequiredMixin, DetailView):
    template_name = 'project/project_view.html'
    model = Project


class ProjectCreate(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    model = Project
    form_class = ProjectForm
    permission_required = 'webapp.add_project'

    def form_valid(self, form):
        form.save()
        form.instance.author.add(self.request.user.pk)
        return super().form_valid(form)


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/project_update.html'
    form_class = ProjectForm
    context_object_name = "projects"
    permission_required = 'webapp.change_project'


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    context_object_name = "projects"
    permission_required = 'webapp.delete_project'
    success_url = reverse_lazy('webapp:project_index')

source/webapp/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.utils.http import urlencode
from django.shortcuts import get_object_or_404, reverse
from webapp.models import Task, Project
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from webapp.form import TaskForm, SearchForm


# Create your views here.


class TaskIndex(LoginRequiredMixin, ListView):
    template_name = 'task/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ['-created_at']
    paginate_by = 10
    paginate_orphans = 5

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class TaskView(LoginRequiredMixin, DetailView):
    template_name = 'task/task_view.html'
    model = Task


class TaskCreate(PermissionRequiredMixin, CreateView):
    template_name = 'task/task_create.html'
    model = Task
    form_class = TaskForm
    permission_required = 'webapp.add_task'

    def get_success_url(self):
        return reverse('webapp:project', kwargs={'pk': self.object.project.pk})

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        form.instance.project = project
        return super().form_valid(form)

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.author.all()


class TaskUpdate(PermissionRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/task_update.html'
    form_class = TaskForm
    context_object_name = "projects"
    permission_required = 'webapp.change_task'

    def get_success_url(self):
        return reverse('webapp:project', kwargs={'pk': self.object.project.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.author.all()


class TaskDelete(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = 'task/task_delete.html'
    context_object_name = 'task'
    permission_required = 'webapp.delete_task'

    def get_success_url(self):
        return reverse('webapp:project', kwargs={'pk': self.object.project.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.author.all()

source/webapp/templates/partial/form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{% for error in form.non_field_errors%}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{%for field in form%}
    <div class="form-check">
        <p><label for="{{ field.id_for_label }}">{{field.label}}</label></p>
        {% for error in field.errors%}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
        <p>{{ field }}</p>
    </div>
{% endfor %}

{% if not fields_only %}
<input  type="submit" value="{{ button_text }}" class="btn btn-success mx-4"/>
{% endif %}

source/webapp/templates/partial/pagination.html
<ul class="pagination justify-content-center pt-4">

    {% if not page_obj.has_previous %}
        <li class="page-item disabled">
            <a class="page-link" href="#">First</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% else %}
        <li class="page-item ">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page=1">First</a>
        </li>
        <li class="page-item ">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link"
        href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
    {% endif %}

    <li class="page-item"><a class="page-link"
        href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.number }}">{{ page_obj.number }}</a>
    </li>

    {% if not page_obj.has_next %}
        <li class="page-item disabled">
            <a class="page-link" href="#">End</a>
        </li>

        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% else %}
        <li class="page-item"><a class="page-link"
        href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>

        <li class="page-item ">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>

        <li class="page-item ">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ paginator.num_pages }}">End</a>
        </li>
    {% endif %}

</ul>

source/webapp/templates/partial/project_list_partial.html
<h1 style="text-align: center">Project Tracker <i class="bi bi-bookmark-check"></i></h1>
    <div class="row">
    {% for project in projects %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body" style="font-weight: bold">
            <h2><a href="{% url 'webapp:project' project.pk %}" style="text-decoration: none">{{ project.summary }} </a></h2>
            <button id="button" data-like-value="{% url 'webapp:project_like' project.pk %}"><i class="bi bi-hand-thumbs-up"></i></button>
            <p>{{ project.description }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
{% if is_paginated %}
        {% include 'partial/pagination.html' %}
{% endif %}